// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      jquery: 'libs/jquery.min',
      underscore: 'libs/underscore.min',
      backbone: 'libs/backbone.min',
      accordionView: 'views/AccordionView',
      templates: '../templates'
    }
  });

  require(['app'], function(App) {
    return App.initialize();
  });

}).call(this);
