// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var AccordionView;
    return AccordionView = Backbone.View.extend({
      el: $('#main'),
      initialize: function() {
        console.info('[AccordionView initialize]');
        _.bindAll(this, 'render');
        return this.render();
      },
      render: function() {
        return $(this.el).append('[AccordionView render]');
      }
    });
  });

}).call(this);
